UPDATE TJRJ.TJRJ_AVISO_COMUNIC_INTIMACAO avci
SET AVCI_IN_1A_VISTA_MPRJ = 'N'
WHERE AVCI_IN_1A_VISTA_MPRJ = 'S' 
AND AVCI_DK IN
(
	SELECT DISTINCT AVCI_DK FROM 
	(
		SELECT 
			avci.AVCI_CD_PROCESSO_CNJ	, 
			avci.AVCI_DK ,
			avci.AVCI_EDCW_DK		AS ID_WEBS,
			acos.ACOS_DT_INCLUSAO AS DT_STATUS ,
			avci.AVCI_TEIP_DK ,
			teip.TEIP_NM_ESTADO_INTIMACAO ,
			avci.AVCI_IN_1A_VISTA_MPRJ,
			TJRJ.TJRJ_PA_INTEGRA_SECRETARIA.is_1a_intimacao_mprj(avci.AVCI_DK) AS VALOR_CORRETO
		FROM TJRJ.TJRJ_AVISO_COMUNIC_INTIMACAO avci
			INNER JOIN TJRJ.TJRJ_AVISO_COMUNIC_STATUS ACOS 
				ON ACOS.ACOS_AVCI_DK = avci_dk
				AND acos.ACOS_IN_ULTIMO_STATUS = 'S'
			LEFT JOIN TJRJ.TJRJ_ESTADO_INTIMACAO_PORTAL TEIP    
				on TEIP.teip_dk = avci_teip_dk
		WHERE 1=1
		AND avci.AVCI_NR_INSTANCIA_PROC = 1
		AND avci.AVCI_DT_DISPONIB_INTIMACAO >= to_date('15/09/2022', 'dd/mm/yyyy') 
		AND avci.AVCI_IN_1A_VISTA_MPRJ IS NOT NULL
		AND avci.AVCI_TEIP_DK NOT IN (5, 7) 
		AND avci.AVCI_CD_PROCESSO_CNJ in
		(
			SELECT AVCI2.AVCI_CD_PROCESSO_CNJ
			FROM TJRJ.TJRJ_AVISO_COMUNIC_INTIMACAO avci2
			WHERE 1=1
			AND AVCI_DT_DISPONIB_INTIMACAO >= to_date('01/01/2022', 'dd/mm/yyyy')
			AND avci2.AVCI_NR_INSTANCIA_PROC = 1
			AND avci2.AVCI_IN_1A_VISTA_MPRJ = 'S'
			AND avci2.AVCI_TEIP_DK NOT IN (5, 7) 
			GROUP BY avci2.AVCI_CD_PROCESSO_CNJ
			HAVING count(*) > 1
		)
		ORDER BY 1, 2 
	)
	WHERE 1=1
	AND AVCI_IN_1A_VISTA_MPRJ = 'S'
	AND AVCI_IN_1A_VISTA_MPRJ <> VALOR_CORRETO
);
commit;