ALTER TABLE TJRJ.TJRJ_PJE_PROCED_ORIGEM
DROP ( PJPO_NR_PROCED );

ALTER TABLE TJRJ.TJRJ_PJE_PROCED_ORIGEM
ADD ( PJPO_NR_PROCED VARCHAR2(100) NULL );

ALTER TABLE TJRJ.TJRJ_PJE_DOC_COMUNIC
DROP ( PJDC_TP_DOCUMENTO );

ALTER TABLE TJRJ.TJRJ_PJE_DOC_COMUNIC
ADD ( PJDC_TP_DOCUMENTO    VARCHAR2(100) NULL );