INSERT INTO TJRJ_PREVENCAO tpp
(
	TPRV_DK,
	TRPV_ORGE_FK,
	TPRV_ORGI_DK,
	TPRV_TOPR_DK,
	TPRV_CD_PROCESSO_CNJ,
	TPRV_CPF_OPERADOR,
	TPRV_OBSERVACAO,
	TPRV_DT_INCLUSAO,
	TPRV_INSTANCIA_PROC,
	TPRV_IN_RESTRITO_CAMARA,
	TPRV_IN_REGRA_ATIVA,
	TPRV_DT_INATIVACAO
)
SELECT
	tjrj.TJRJ_SQ_TPRV_DK.NEXTVAL	AS TPRV_DK , 
	NULL 							AS TRPV_ORGE_FK ,
	PJPC_ORGI_DK					AS TPRV_ORGI_DK ,
	PJPC_PJOP_DK					AS TPRV_TOPR_DK ,
	PJPC_CD_PROCESSO_CNJ			AS TPRV_CD_PROCESSO_CNJ ,
	PJPC_CPF_OPERADOR				AS TPRV_CPF_OPERADOR,
	PJPC_OBSERVACAO					AS TPRV_OBSERVACAO ,
	PJPC_DT_INCLUSAO 				AS TPRV_DT_INCLUSAO ,
	1								AS TPRV_INSTANCIA_PROC ,
	NULL							AS TPRV_IN_RESTRITO_CAMARA ,
	PJPC_IN_REGRA_ATIVA				AS TPRV_IN_REGRA_ATIVA,
	PJPC_DT_INATIVACAO				AS TPRV_DT_INATIVACAO
FROM
	TJRJ_PJE_PREVENCAO tpp ;
COMMIT;