CREATE TABLE TJRJ.TJRJ_PJE_UNIDADE_PRISIONAL
(
	PJUP_DK              NUMBER 		NOT NULL ,
	PJUP_ID_UNIDADE      NUMBER 		NOT NULL ,
	PJUP_NM_UNIDADE      VARCHAR2(100)	NOT NULL ,
	PJUP_DT_INCLUSAO     DATE 			NOT NULL ,
	CONSTRAINT  PJUP_PK PRIMARY KEY (PJUP_DK)
);

ALTER TABLE TJRJ.TJRJ_PJE_UNIDADE_PRISIONAL
ADD CONSTRAINT PJUP_ID_UNIDADE_UK UNIQUE (PJUP_ID_UNIDADE);

	grant select, insert, delete, update on TJRJ.TJRJ_PJE_UNIDADE_PRISIONAL TO RL_TJRJ_WEBSERV;
		
	create sequence TJRJ.TJRJ_SQ_PJUP_DK START WITH 1 INCREMENT BY 1 NOORDER NOCACHE NOCYCLE ;
	grant select on TJRJ.TJRJ_SQ_PJUP_DK TO RL_TJRJ_WEBSERV;

COMMENT ON TABLE TJRJ.TJRJ_PJE_UNIDADE_PRISIONAL IS 'Unidade prisional onde se realizou o referido evento criminal. Tabela de domínio.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_UNIDADE_PRISIONAL.PJUP_ID_UNIDADE IS 'Identificador da Unidade Prisional, de uso do CNJ.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_UNIDADE_PRISIONAL.PJUP_NM_UNIDADE IS 'Nome da Unidade Prisional.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_UNIDADE_PRISIONAL.PJUP_DK IS 'Primary key baseada em sequence.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_UNIDADE_PRISIONAL.PJUP_DT_INCLUSAO IS 'Data em que foi incluída esta Unidade Prisional na base de dados.';

CREATE TABLE TJRJ.TJRJ_PJE_MOTIVO_PRISAO
(
	PJMP_DK              NUMBER 		NOT NULL ,
	PJMP_ID_MOTIVO       VARCHAR2(30) 	NOT NULL ,
	PJMP_DS_MOTIVO       VARCHAR2(200) 	NOT NULL ,
	PJMP_DT_INCLUSAO     DATE 			NOT NULL ,
	CONSTRAINT  PJMP_PK PRIMARY KEY (PJMP_DK)
);

ALTER TABLE TJRJ.TJRJ_PJE_MOTIVO_PRISAO
ADD CONSTRAINT PJMP_ID_MOTIVO_UK UNIQUE (PJMP_ID_MOTIVO);

	grant select, insert, delete, update on TJRJ.TJRJ_PJE_MOTIVO_PRISAO TO RL_TJRJ_WEBSERV;
		
	create sequence TJRJ.TJRJ_SQ_PJMP_DK START WITH 1 INCREMENT BY 1 NOORDER NOCACHE NOCYCLE ;
	grant select on TJRJ.TJRJ_SQ_PJMP_DK TO RL_TJRJ_WEBSERV;

COMMENT ON TABLE TJRJ.TJRJ_PJE_MOTIVO_PRISAO IS 'Tabela de domínio, contendo os Motivos da decretação da prisão conhecidos.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_MOTIVO_PRISAO.PJMP_ID_MOTIVO IS 'Identificador do Motivo da Prisão, utilizado pelo CNJ.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_MOTIVO_PRISAO.PJMP_DS_MOTIVO IS 'Textual descritivo do motivo da prisão.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_MOTIVO_PRISAO.PJMP_DK IS 'Primary key baseada em sequence.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_MOTIVO_PRISAO.PJMP_DT_INCLUSAO IS 'Data em que foi incluído este Motivo de prisão na base de dados.';

CREATE TABLE TJRJ.TJRJ_PJE_MOTIVO_SOLTURA
(
	PJMS_DK              NUMBER 		NOT NULL ,
	PJMS_ID_MOTIVO       VARCHAR2(30) 	NOT NULL ,
	PJMS_DS_MOTIVO       VARCHAR2(200) 	NOT NULL ,
	PJMS_DT_INCLUSAO     DATE 			NOT NULL ,
	CONSTRAINT  PJMS_PK PRIMARY KEY (PJMS_DK)
);

ALTER TABLE TJRJ.TJRJ_PJE_MOTIVO_SOLTURA
ADD CONSTRAINT PJMS_ID_MOTIVO_UK UNIQUE (PJMS_ID_MOTIVO);

	grant select, insert, delete, update on TJRJ.TJRJ_PJE_MOTIVO_SOLTURA TO RL_TJRJ_WEBSERV;
		
	create sequence TJRJ.TJRJ_SQ_PJMS_DK START WITH 1 INCREMENT BY 1 NOORDER NOCACHE NOCYCLE ;
	grant select on TJRJ.TJRJ_SQ_PJMS_DK TO RL_TJRJ_WEBSERV;

COMMENT ON TABLE TJRJ.TJRJ_PJE_MOTIVO_SOLTURA IS 'Tabela de domínio contendo os motivos de soltura conhecidos.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_MOTIVO_SOLTURA.PJMS_DK IS 'Primary key baseada em sequence.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_MOTIVO_SOLTURA.PJMS_ID_MOTIVO IS 'Identificador do motivo de soltura original do CNJ.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_MOTIVO_SOLTURA.PJMS_DS_MOTIVO IS 'Textual descritivo do motivo de soltura.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_MOTIVO_SOLTURA.PJMS_DT_INCLUSAO IS 'Data em que foi incluído este Motivo de soltura na base de dados.';

CREATE TABLE TJRJ.TJRJ_PJE_EVENTO_CRIMINAL
(
	PJEC_DK              NUMBER 	NOT NULL ,
	PJEC_PJPA_DK         NUMBER 	NOT NULL ,	
	PJEC_PJUP_DK         NUMBER 	NOT NULL ,	
	PJEC_DT_EVENTO       DATE 		NOT NULL ,
	CONSTRAINT  PJEC_PK PRIMARY KEY (PJEC_DK)
);


ALTER TABLE TJRJ.TJRJ_PJE_EVENTO_CRIMINAL
ADD CONSTRAINT PJEC_PJPA_FK FOREIGN KEY (PJEC_PJPA_DK) 
REFERENCES TJRJ.TJRJ_PJE_PARTE (PJPA_DK);

	CREATE  INDEX TJRJ.PJEC_PJPA_FK_I 
	ON TJRJ.TJRJ_PJE_EVENTO_CRIMINAL (PJEC_PJPA_DK   ASC);

ALTER TABLE TJRJ.TJRJ_PJE_EVENTO_CRIMINAL
ADD CONSTRAINT PJEC_PJUP_FK FOREIGN KEY (PJEC_PJUP_DK) 
REFERENCES TJRJ.TJRJ_PJE_UNIDADE_PRISIONAL (PJUP_DK);

	CREATE  INDEX TJRJ.PJEC_PJUP_FK_I 
	ON TJRJ.TJRJ_PJE_EVENTO_CRIMINAL (PJEC_PJUP_DK   ASC);	
	
	grant select, insert, delete, update on TJRJ.TJRJ_PJE_EVENTO_CRIMINAL TO RL_TJRJ_WEBSERV;
		
	create sequence TJRJ.TJRJ_SQ_PJEC_DK START WITH 1 INCREMENT BY 1 NOORDER NOCACHE NOCYCLE ;
	grant select on TJRJ.TJRJ_SQ_PJEC_DK TO RL_TJRJ_WEBSERV;
	
COMMENT ON TABLE TJRJ.TJRJ_PJE_EVENTO_CRIMINAL IS 'Envento criminal associado à uma parte, num processo criminal. Ex: prisão da parte, em determinada unidade prisional - soltura de parte - fuga de parte.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_EVENTO_CRIMINAL.PJEC_PJPA_DK IS 'FK para TJRJ_PJE_PARTE.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_EVENTO_CRIMINAL.PJEC_DT_EVENTO IS 'Data em que ocorreu o evento criminal (ex: data da prisão da referida parte, data da soltura da parte).';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_EVENTO_CRIMINAL.PJEC_DK IS 'Primary key baseada em sequence.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_EVENTO_CRIMINAL.PJEC_PJUP_DK IS 'FK para TJRJ_UNIDADE_PRISIONAL.';

CREATE TABLE TJRJ.TJRJ_PJE_FUGA
(
	PJFU_DK              NUMBER  		NOT NULL ,
	PJFU_DS_FUGA         VARCHAR2(500) 	NULL ,
	PJFU_PJEC_DK         NUMBER 		NOT NULL ,
	CONSTRAINT  PJFU_PK PRIMARY KEY (PJFU_DK)
);

ALTER TABLE TJRJ.TJRJ_PJE_FUGA
ADD CONSTRAINT PJFU_PJEC_FK FOREIGN KEY (PJFU_PJEC_DK) 
REFERENCES TJRJ.TJRJ_PJE_EVENTO_CRIMINAL (PJEC_DK);

	CREATE  INDEX TJRJ.PJFU_PJEC_FK_I 
	ON TJRJ.TJRJ_PJE_FUGA (PJFU_PJEC_DK   ASC);

	grant select, insert, delete, update on TJRJ.TJRJ_PJE_FUGA TO RL_TJRJ_WEBSERV;
		
	create sequence TJRJ.TJRJ_SQ_PJFU_DK START WITH 1 INCREMENT BY 1 NOORDER NOCACHE NOCYCLE ;
	grant select on TJRJ.TJRJ_SQ_PJFU_DK TO RL_TJRJ_WEBSERV;

COMMENT ON TABLE TJRJ.TJRJ_PJE_FUGA IS 'Evento de fuga realizada por uma das partes de um processo criminal.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_FUGA.PJFU_DK IS 'Primary key baseada em sequence.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_FUGA.PJFU_DS_FUGA IS 'Textual descritivo do evento da fuga.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_FUGA.PJFU_PJEC_DK IS 'FK para TJRJ_PJE_EVENTO_CRIMINAL.';

CREATE TABLE TJRJ.TJRJ_PJE_PRISAO
(
	PJPI_DK              NUMBER NOT NULL ,
	PJPI_PJMP_DK         NUMBER NOT NULL ,
	PJPI_PJEC_DK         NUMBER NOT NULL ,
	PJPI_PRAZO_DIAS      NUMBER NULL ,
	PJPI_PRAZO_MESES     NUMBER NULL ,
	PJPI_PRAZO_ANOS      NUMBER NULL ,
	CONSTRAINT  PJPI_PK PRIMARY KEY (PJPI_DK)
);

ALTER TABLE TJRJ.TJRJ_PJE_PRISAO
	ADD CONSTRAINT PJPI_PJMP_FK FOREIGN KEY (PJPI_PJMP_DK) 
	REFERENCES TJRJ.TJRJ_PJE_MOTIVO_PRISAO (PJMP_DK);
	
	CREATE  INDEX TJRJ.PJPI_PJMP_FK_I 
	ON TJRJ.TJRJ_PJE_PRISAO (PJPI_PJMP_DK   ASC);

ALTER TABLE TJRJ.TJRJ_PJE_PRISAO
	ADD CONSTRAINT PJPI_PJEC_FK FOREIGN KEY (PJPI_PJEC_DK) 
	REFERENCES TJRJ.TJRJ_PJE_EVENTO_CRIMINAL (PJEC_DK);
	
	CREATE  INDEX TJRJ.PJPI_PJEC_FK_I 
	ON TJRJ.TJRJ_PJE_PRISAO (PJPI_PJEC_DK   ASC);

	grant select, insert, delete, update on TJRJ.TJRJ_PJE_PRISAO TO RL_TJRJ_WEBSERV;
		
	create sequence TJRJ.TJRJ_SQ_PJPI_DK START WITH 1 INCREMENT BY 1 NOORDER NOCACHE NOCYCLE ;
	grant select on TJRJ.TJRJ_SQ_PJPI_DK TO RL_TJRJ_WEBSERV;

COMMENT ON TABLE TJRJ.TJRJ_PJE_PRISAO IS 'Sentença de prisão emitida contra uma das partes do processo criminal.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_PRISAO.PJPI_PRAZO_DIAS IS 'Prazo em dias decretado para a prisão.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_PRISAO.PJPI_PRAZO_MESES IS 'Prazo em meses decretado para a prisão.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_PRISAO.PJPI_PRAZO_ANOS IS 'Prazo em anos decretado para a prisão.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_PRISAO.PJPI_DK IS 'Primary key baseada em sequence.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_PRISAO.PJPI_PJMP_DK IS 'FK para TJTJ_PJE_MOTIVO_PRISAO.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_PRISAO.PJPI_PJEC_DK IS 'FK para TJRJ_PJE_EVENTO_CRIMINAL.';

CREATE TABLE TJRJ.TJRJ_PJE_SOLTURA
(
	PJSO_DK              NUMBER NOT NULL ,
	PJSO_PJMS_DK         NUMBER NOT NULL ,
	PJSO_PJEC_DK         NUMBER NOT NULL ,
	CONSTRAINT  PJSO_PK PRIMARY KEY (PJSO_DK)
);

ALTER TABLE TJRJ.TJRJ_PJE_SOLTURA
ADD CONSTRAINT PJSO_PJMS_FK FOREIGN KEY (PJSO_PJMS_DK) 
REFERENCES TJRJ.TJRJ_PJE_MOTIVO_SOLTURA (PJMS_DK);

	CREATE  INDEX TJRJ.PJSO_PJMS_FK_I 
	ON TJRJ.TJRJ_PJE_SOLTURA (PJSO_PJMS_DK   ASC);

ALTER TABLE TJRJ.TJRJ_PJE_SOLTURA
ADD CONSTRAINT PJSO_PJEC_FK FOREIGN KEY (PJSO_PJEC_DK) 
REFERENCES TJRJ.TJRJ_PJE_EVENTO_CRIMINAL (PJEC_DK);

	CREATE  INDEX TJRJ.PJSO_PJEC_FK_I 
	ON TJRJ.TJRJ_PJE_SOLTURA (PJSO_PJEC_DK   ASC);

	grant select, insert, delete, update on TJRJ.TJRJ_PJE_SOLTURA TO RL_TJRJ_WEBSERV;
		
	create sequence TJRJ.TJRJ_SQ_PJSO_DK START WITH 1 INCREMENT BY 1 NOORDER NOCACHE NOCYCLE ;
	grant select on TJRJ.TJRJ_SQ_PJSO_DK TO RL_TJRJ_WEBSERV;

COMMENT ON TABLE TJRJ.TJRJ_PJE_SOLTURA IS 'Evento de soltura (de uma prisão) de uma das partes.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_SOLTURA.PJSO_DK IS 'Primary key baseada em sequence.';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_SOLTURA.PJSO_PJMS_DK IS 'FK para TJRJ_PJE_MOTIVO_SOLTURA';
COMMENT ON COLUMN TJRJ.TJRJ_PJE_SOLTURA.PJSO_PJEC_DK IS 'FK para TJRJ_PJE_EVENTO_CRIMINAL.';