-- DROP TABLE TJRJ.TEST_TABLE ;
CREATE TABLE TJRJ.TEST_TABLE
(
	IDX			NUMBER 			NOT NULL,
	DESCRICAO	VARCHAR(100)	NOT NULL,
	CONSTRAINT PK_TEST PRIMARY KEY(IDX)
);

INSERT INTO TJRJ.TEST_TABLE (IDX, DESCRICAO) VALUES (1, 'BANANA');
INSERT INTO TJRJ.TEST_TABLE (IDX, DESCRICAO) VALUES (2, 'LARANJA');
INSERT INTO TJRJ.TEST_TABLE (IDX, DESCRICAO) VALUES (3, 'ABACAXI');
COMMIT;
-- SELECT * FROM TJRJ.TEST_TABLE ;