CREATE OR REPLACE VIEW TJRJ.TJRJ_VW_AVISO_TAG 
(
	VWAT_AVCI_DK			,
	VWAT_TAAV_DK			,
	VWAT_TGPR_DK			,
	VWAT_TIPO_ASSOCIACAO	,
	VWAT_ORDENACAO			,
	VWAT_CD_PROCESSO_CNJ	,
	VWAT_NR_INSTANCIA_PROC	,
	VWAT_TJRA_DK			,
	VWAT_TACU_DK			,
	VWAT_ORGI_DK			,
	VWAT_DS_TAG				,
	VWAT_NM_COR_TAG			,
	VWAT_DT_ASSOC_TAG
) 
AS 
  SELECT 
	VWAT_AVCI_DK			,
	VWAT_TAAV_DK			,
	VWAT_TGPR_DK			,
	VWAT_TIPO_ASSOCIACAO	,
	VWAT_ORDENACAO			,
	VWAT_CD_PROCESSO_CNJ	,
	VWAT_NR_INSTANCIA_PROC	,
	VWAT_TJRA_DK			,
	VWAT_TACU_DK			,
	VWAT_ORGI_DK			,
	VWAT_DS_TAG				,
	VWAT_NM_COR_TAG 		,
	VWAT_DT_ASSOC_TAG
  FROM 
	(
		SELECT
			avc.AVCI_DK						AS VWAT_AVCI_DK				,
			tgav.TAAV_DK 					AS VWAT_TAAV_DK				,
			NULL							AS VWAT_TGPR_DK				,
			'I'								AS VWAT_TIPO_ASSOCIACAO		,
			tgav.TAAV_ORDENACAO 			AS VWAT_ORDENACAO			, 
			avc.AVCI_CD_PROCESSO_CNJ		AS VWAT_CD_PROCESSO_CNJ		,
			avc.AVCI_NR_INSTANCIA_PROC		AS VWAT_NR_INSTANCIA_PROC	,
			avc.AVCI_TJRA_DK				AS VWAT_TJRA_DK				,
			tag.TACU_DK						AS VWAT_TACU_DK				,
			tag.TACU_ORGI_DK				AS VWAT_ORGI_DK				,
			tag.TACU_DS_TAG					AS VWAT_DS_TAG				,
			tag.TACU_NM_COR_TAG				AS VWAT_NM_COR_TAG			,
			tgav.TAAV_DT_INCLUSAO			AS VWAT_DT_ASSOC_TAG
		FROM TJRJ_AVISO_COMUNIC_INTIMACAO avc 
			inner JOIN TJRJ.TJRJ_TAG_AVISO tgav ON tgav.TAAV_AVCI_DK = avc.AVCI_DK 
			inner JOIN TJRJ.TJRJ_TAG_CUSTOMIZADA tag ON tag.TACU_DK = TGAV.TAAV_TACU_DK 
		WHERE tag.TACU_ORGI_DK = avc.AVCI_ORGI_DK
		
		UNION
		
		SELECT 
			AVC.AVCI_DK 					AS VWAT_AVCI_DK				,
			NULL		 					AS VWAT_TAAV_DK				,
			TAPR.TGPR_DK 					AS VWAT_TGPR_DK				,
			'P'								AS VWAT_TIPO_ASSOCIACAO		,
			TAPR.TGPR_ORDENACAO  			AS VWAT_ORDENACAO			, 
			avc.AVCI_CD_PROCESSO_CNJ 		AS VWAT_CD_PROCESSO_CNJ		,
			1								AS VWAT_NR_INSTANCIA_PROC	,
			TJRA.TJRA_DK					AS VWAT_TJRA_DK				,
			tag.TACU_DK						AS VWAT_TACU_DK				,
			tag.TACU_ORGI_DK				AS VWAT_ORGI_DK				,
			tag.TACU_DS_TAG					AS VWAT_DS_TAG				,
			tag.TACU_NM_COR_TAG				AS VWAT_NM_COR_TAG			,
			tapr.TGPR_DT_INCLUSAO 			AS VWAT_DT_ASSOC_TAG		
		FROM TJRJ.TJRJ_TAG_PROCESSO_AVISO TAPR 
			INNER JOIN TJRJ_PROCESSO_AVISO TJRA   ON TJRA.TJRA_DK = TAPR.TGPR_TJRA_DK 
			INNER JOIN TJRJ_AVISO_COMUNIC_INTIMACAO avc ON avc.AVCI_TJRA_DK = TJRA.TJRA_DK
		INNER JOIN TJRJ.TJRJ_TAG_CUSTOMIZADA tag ON tag.TACU_DK = TAPR.TGPR_TACU_DK 
		WHERE tag.TACU_ORGI_DK = avc.AVCI_ORGI_DK
	)
	WHERE 1=1
	ORDER BY 
		VWAT_AVCI_DK ASC ,
		VWAT_TIPO_ASSOCIACAO 	ASC	,
		VWAT_ORDENACAO 			ASC
	;

GRANT SELECT ON TJRJ.TJRJ_VW_AVISO_TAG TO RL_TJRJ_WEBSERV;
GRANT SELECT ON TJRJ.TJRJ_VW_AVISO_TAG TO RL_INTG_JUDI;

COMMENT ON TABLE TJRJ.TJRJ_VW_AVISO_TAG IS 'View que exibe as tags associadas a um aviso ou ao processo associado ao aviso.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_AVISO_TAG.VWAT_AVCI_DK IS 'Id do aviso que está associado a Tags';
COMMENT ON COLUMN TJRJ.TJRJ_VW_AVISO_TAG.VWAT_TAAV_DK IS 'Id da associação entre um aviso e uma tag. DK da tabela TJRJ_TAG_AVISO.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_AVISO_TAG.VWAT_TGPR_DK IS 'Id da associação entre um processo e uma tag. DK da tabela TJRJ_TAG_PROCESSO_AVISO.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_AVISO_TAG.VWAT_TIPO_ASSOCIACAO IS 'Tipo de associação da tag: (I) associação à Intimacao, (P) associação ao Processo';
COMMENT ON COLUMN TJRJ.TJRJ_VW_AVISO_TAG.VWAT_ORDENACAO IS 'Ordenção da Tag';
COMMENT ON COLUMN TJRJ.TJRJ_VW_AVISO_TAG.VWAT_CD_PROCESSO_CNJ IS 'Código do Processo (CNJ) associado ao aviso.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_AVISO_TAG.VWAT_NR_INSTANCIA_PROC IS 'Instância processual associada ao aviso.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_AVISO_TAG.VWAT_TJRA_DK IS 'Id do Processo-aviso ao qual o aviso esta associado. FK para TJRJ_PROCESSO_AVISO.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_AVISO_TAG.VWAT_TACU_DK IS 'Id da tag que está sendo listada. FK para TJRJ_TAG_CUSTOMIZADA.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_AVISO_TAG.VWAT_ORGI_DK IS 'Id do órgão ao qual a tag está associada. Fk para ORGI_ORGAO.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_AVISO_TAG.VWAT_DS_TAG IS 'Texto da Tag. Ex: Prioridade';
COMMENT ON COLUMN TJRJ.TJRJ_VW_AVISO_TAG.VWAT_NM_COR_TAG IS 'Nome da cor a ser aplicada à Tag, de acordo com o padrão da equipe de front-end. Ex: SUCCESS_LIGHTEST.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_AVISO_TAG.VWAT_DT_ASSOC_TAG IS 'Data da associação da Tag ao Aviso ou ao Processo.';

CREATE OR REPLACE VIEW TJRJ.TJRJ_VW_PROCESSO_DERIVADO
(
		TPDV_AVCI_DK_PRC_ORIG			,
		TPDV_NR_CNJ_PRC_ORIG			,
		TPDV_NR_INST_PRC_ORIG			,
		TPDV_OINT_DK_PRC_ORIG			,
		TPDV_CD_ID_AVISO_ORIG			,
		TPDV_AVCI_DK_PRC_DERIV			,
		TPDV_CD_ID_AVISO_DERIV			,
		TPDV_DT_DISPONIB_PRC_DERIV		,
		TPDV_NR_CNJ_PRC_DERIV			,
		TPDV_CD_PRC_UNICO_DERIV			,
		TPDV_AVCI_TJRA_DK				,
		TPDV_NR_INST_PRC_DERIV			,
		TPDV_OINT_DK_PRC_DERIV			,
		TPDV_CLDC_DK_PRC_DERIV			,
		TPDV_ORGI_DISTR_PRC_DERIV		,
		TPDV_TEIP_DK_PRC_DERIV			,
		TPDV_CD_ORG_JULG_PRC_DERIV		,
		TPDV_NM_ORG_JULG_PRC_DERIV	
)
AS 
   SELECT
		avc_orig.AVCI_DK 					AS TPDV_AVCI_DK_PRC_ORIG			,
		avc_orig.AVCI_CD_PROCESSO_CNJ		AS TPDV_NR_CNJ_PRC_ORIG				,
		avc_orig.AVCI_NR_INSTANCIA_PROC		AS TPDV_NR_INST_PRC_ORIG			,
		avc_orig.AVCI_OINT_DK 				AS TPDV_OINT_DK_PRC_ORIG			,
		avc_orig.AVCI_CD_ID_AVISO			AS TPDV_CD_ID_AVISO_ORIG			, 
		avc_deriv.AVCI_DK 						AS TPDV_AVCI_DK_PRC_DERIV		,
		avc_deriv.AVCI_CD_ID_AVISO				AS TPDV_CD_ID_AVISO_DERIV		, 
		avc_deriv.AVCI_DT_DISPONIB_INTIMACAO	AS TPDV_DT_DISPONIB_PRC_DERIV	,
		avc_deriv.AVCI_CD_PROCESSO_CNJ			AS TPDV_NR_CNJ_PRC_DERIV		,
		avc_deriv.AVCI_CD_PROCESSO_UNICO  		AS TPDV_CD_PRC_UNICO_DERIV		,
		avc_deriv.AVCI_TJRA_DK					AS TPDV_AVCI_TJRA_DK			, 
		avc_deriv.AVCI_NR_INSTANCIA_PROC		AS TPDV_NR_INST_PRC_DERIV		,
		avc_deriv.AVCI_OINT_DK					AS TPDV_OINT_DK_PRC_DERIV		,
		avc_deriv.AVCI_CLDC_DK					AS TPDV_CLDC_DK_PRC_DERIV		,
		avc_deriv.AVCI_ORGI_DK					AS TPDV_ORGI_DISTR_PRC_DERIV	,
		avc_deriv.AVCI_TEIP_DK					AS TPDV_TEIP_DK_PRC_DERIV		,
		avc_deriv.AVCI_CD_ORGAO_JULGADOR		AS TPDV_CD_ORG_JULG_PRC_DERIV	,
		avc_deriv.AVCI_NM_ORGAO_JULGADOR		AS TPDV_NM_ORG_JULG_PRC_DERIV	
     FROM TJRJ.TJRJ_AVISO_COMUNIC_INTIMACAO avc_orig
     INNER JOIN TJRJ.TJRJ_AVISO_COMUNIC_INTIMACAO avc_deriv
     	ON avc_deriv.AVCI_CD_PROCESSO_ORIGINARIO = avc_orig.AVCI_CD_PROCESSO_CNJ
     	AND avc_deriv.AVCI_TEIP_DK NOT IN (7) 
    WHERE   1=1
		AND avc_orig.AVCI_NR_INSTANCIA_PROC = 1 
		AND avc_deriv.AVCI_NR_INSTANCIA_PROC = 2 
    ;
   
GRANT SELECT ON TJRJ.TJRJ_VW_PROCESSO_DERIVADO TO RL_TJRJ_WEBSERV;
GRANT SELECT ON TJRJ.TJRJ_VW_PROCESSO_DERIVADO TO RL_INTG_JUDI;
   
COMMENT ON TABLE TJRJ.TJRJ_VW_PROCESSO_DERIVADO IS 'View que relaciona avisos de processos (de 2ª instância) (processos "derivados") ao processo de 1ª instância que lhes deu origem (processo originário).';
COMMENT ON COLUMN TJRJ.TJRJ_VW_PROCESSO_DERIVADO.TPDV_AVCI_DK_PRC_ORIG IS 'Identificado do processo priginário. Corresponde a AVCI_DK.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_PROCESSO_DERIVADO.TPDV_NR_CNJ_PRC_ORIG IS 'Número (CNJ) do Processo, referente ao processo originário.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_PROCESSO_DERIVADO.TPDV_NR_INST_PRC_ORIG IS 'Instância processual do aviso do processo originário.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_PROCESSO_DERIVADO.TPDV_OINT_DK_PRC_ORIG IS 'Sistema de origem do aviso do processo originário. Fk para TJRJ_ORIGEM_INTIMACAO.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_PROCESSO_DERIVADO.TPDV_AVCI_DK_PRC_DERIV IS 'Instância processual do aviso do processo derivado.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_PROCESSO_DERIVADO.TPDV_DT_DISPONIB_PRC_DERIV IS 'Data de disponibilização do aviso do processo derivado.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_PROCESSO_DERIVADO.TPDV_NR_CNJ_PRC_DERIV IS 'Número (CNJ) do Processo, referente ao processo derivado.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_PROCESSO_DERIVADO.TPDV_CD_PRC_UNICO_DERIV IS 'Número do processo único, do processo derivado.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_PROCESSO_DERIVADO.TPDV_NR_INST_PRC_DERIV IS 'Instância processual do aviso do processo derivado.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_PROCESSO_DERIVADO.TPDV_OINT_DK_PRC_DERIV IS 'Sistema de origem do aviso do processo derivado. Fk para TJRJ_ORIGEM_INTIMACAO.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_PROCESSO_DERIVADO.TPDV_CLDC_DK_PRC_DERIV IS 'Classe processual do processo derivado. FK para a tabela MCPR.MCPR_CLASSE_DOCTO_MP.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_PROCESSO_DERIVADO.TPDV_ORGI_DISTR_PRC_DERIV IS 'Id do Último órgão de distribuido do aviso do processo derivado. FK para ORGI.ORGI_ORGAO.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_PROCESSO_DERIVADO.TPDV_TEIP_DK_PRC_DERIV IS 'Id do Status do aviso do processo derivado. FK para TJRJ_ESTADO_INTIMACAO_PORTAL.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_PROCESSO_DERIVADO.TPDV_CD_ORG_JULG_PRC_DERIV IS 'Código do órgão julgador do aviso do processo derivado. Corresponde a AVCI_CD_ORGAO_JULGADOR.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_PROCESSO_DERIVADO.TPDV_NM_ORG_JULG_PRC_DERIV IS 'Nome do órgão julgador do aviso do processo derivado. Corresponde a TPDV_NM_ORG_JULG_PRC_DERIV.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_PROCESSO_DERIVADO.TPDV_CD_ID_AVISO_ORIG IS 'Código que identifica o aviso de uma intimação do TJRJ ao MPRJ - referente ao processo originário.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_PROCESSO_DERIVADO.TPDV_CD_ID_AVISO_DERIV IS 'Código que identifica o aviso de uma intimação do TJRJ ao MPRJ - referente ao processo derivado.';
COMMENT ON COLUMN TJRJ.TJRJ_VW_PROCESSO_DERIVADO.TPDV_AVCI_TJRA_DK IS 'FK para a tabela TJRJ_PROCESSO_AVISO. Corresponde a AVCI_TJRA_DK, para o processo derivado.'
