UPDATE TJRJ_AVISO_COMUNIC_INTIMACAO avc
SET AVCI_TP_COMUNICACAO = 'INT'
WHERE avc.AVCI_TEIP_DK IN (7, 8, 4)
  AND avc.AVCI_DT_DISPONIB_INTIMACAO >= to_date('01/01/2024', 'dd/mm/yyyy')
  AND AVCI_TP_COMUNICACAO IS NULL 
  AND NVL(avc.AVCI_IN_PROC_NAO_INTIMADO, 'N') = 'N';

commit;