pipeline {
	agent any

	tools {nodejs "nodejs"}

	stages {

		stage("Dependencias") {
			steps {
				sh 'cd ExecutaDbOracle \
				npm install'
			}			
		}
		
		stage("Gera Massa") {
			steps {
				sh 'cd ExecutaDbOracle \
				exec node GeraMassaTesteDistribuicao.js "10.0.251.32/CORR" TJRJ tjrj63'
			}
		}
		
		stage("Cadastra distribuidores") {
			steps {
				sh 'cd ExecutaDbOracle \
				exec node GeraMassaTesteDistribuicao.js "10.0.251.32/CORR" TJRJ tjrj63'
			}
		}
	}
}
