pipeline {
	agent any

	stages {
	
		stage("Dependencias") {
			steps {
				sh 'npm install'
			}			
		}
		
		stage("Gera Massa") {
			steps {
				sh 'node GeraMassaTesteDistribuicao.js "10.0.251.32/CORR" TJRJ tjrj63'
			}
		}
		
		stage("Cadastra distribuidores") {
			steps {
				sh 'node GeraMassaTesteDistribuicao.js "10.0.251.32/CORR" TJRJ tjrj63'
			}
		}
	}
}
